const fs = require('fs');
const path = require('path');
const _ = require('underscore');
const counter = require('./counter');

var items = {};

// Public API - Fix these CRUD functions ///////////////////////////////////////

exports.create = (text, callback) => {
  counter.getNextUniqueId((err, id) => {
    if (err) {
      throw ('error writing counter');
    } else {
      fs.writeFile(exports.dataDir + `/${id}.txt`, text, (err) => {
        if (err) {
          throw ('error writing counter');
        } else {
          callback(null, { id, text });
        }
      });
    }
  });
};
// each todo entry must be save in its own file
// use unique id generated by getNextUniqueID, create file path
// each time a POST, save a file with the todo item in this folder
// only save todo text in file // id todo item is encoded into its filename
// DO NOT STORE OBEJCT.

exports.readAll = (callback) => {
  var tempArray = [];

  fs.readdir(exports.dataDir, (err, files) => {
    if (err) {
      throw ('error readAll files');
    } else {
      files.forEach(file => {
        tempArray.push({id: file.substring(0, file.length - 4), text: file.substring(0, file.length - 4)});
      });
      // console.log(tempArray)
      callback(err, tempArray);
    }
  });

  // var data = _.map(items, (text, id) => {
  //   return { id, text };
  // });
  // callback(null, data);
};

exports.readOne = (id, callback) => {

  fs.readFile(`${exports.dataDir}/${id}.txt`, (err, contents) => {
    if (err) {
      callback(err);
    } else {
      callback(null, {id, text: contents.toString()});
    }
  });
};

exports.update = (id, text, callback) => {
  fs.readFile(`${exports.dataDir}/${id}.txt`, (err, contents) => {
    if (err) {
      callback(err);
    } else {
      fs.writeFile(`${exports.dataDir}/${id}.txt`, text, (err) => {
        if (err) {
          callback(err);
        } else {
          callback(null, { id, text });
        }
      });
    }
  });
};


exports.delete = (id, callback) => {
  fs.unlink(`${exports.dataDir}/${id}.txt`, (err) => {
    if (err) {
      callback(err);
    } else {
      callback();
    }
  });
};

// Config+Initialization code -- DO NOT MODIFY /////////////////////////////////

exports.dataDir = path.join(__dirname, 'data');

exports.initialize = () => {
  if (!fs.existsSync(exports.dataDir)) {
    fs.mkdirSync(exports.dataDir);
  }
};
